version: "3"

services:
  qna:
    build: .
    network_mode: host
    environment:
      PROXY: ${PROXY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - /home/alex/Code/tinkoff-rag/trained_models:/app/rag/finetuned-e5-base-folds_v3
      - /home/alex/Code/tinkoff-rag/tokenizer:/app/rag/e5-base-tokenizer

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]